# Generated by Django 5.2.8 on 2026-02-12 12:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_code',
            field=models.CharField(default=core.models.generate_room_code, max_length=8, unique=True),
        ),
    ]
