# Generated by Django 5.2.8 on 2026-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_is_suggestions_enabled_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='request_type',
            field=models.CharField(choices=[('invite', 'Invite'), ('join_request', 'Join Request')], default='join_request', max_length=20),
        ),
    ]
