# Generated by Django 5.2.8 on 2026-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participant_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_discoverable',
            field=models.BooleanField(default=True, help_text='Allow others to see this session in Available Sessions'),
        ),
    ]
