# Generated by Django 5.2.8 on 2026-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_is_discoverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsuggestion',
            name='keyword',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
